toc:
  - MapboxClient
  - MapboxStyles
  - MapboxStatic
  - MapboxUploads
  - MapboxDatasets
  - MapboxTilesets
  - MapboxGeocoding
  - MapboxDirections
  - MapboxMatching
  - MapboxMatrix
  - MapboxTokens
  - MapboxTilestats
  - MapboxSurface
